# This action.yml provides a GitHub Action for building NCEP libraries with
# CMake.
# Alex Richert, April 2024
name: 'Build NCEPLIBS'
description: 'Builds and installs requested versions/configurations of various NCEPLIBS'

inputs:
  jasper-version:
    default: ""
  jasper-cmake-args:
    default: ""
  bacio-version:
    default: ""
  bacio-cmake-args:
    default: ""
  bufr-version:
    default: ""
  bufr-cmake-args:
    default: ""
  g2-version:
    default: ""
  g2-cmake-args:
    default: ""
  g2c-version:
    default: ""
  g2c-cmake-args:
    default: ""
  ip-version:
    default: ""
  ip-cmake-args:
    default: ""
  sp-version:
    default: ""
  sp-cmake-args:
    default: ""
  w3emc-version:
    default: ""
  w3emc-cmake-args:
    default: ""
  repo-cache:
    description: 'Cache built packages through "actions/cache"'
    default: false

runs:
  using: "composite"

  steps:

    - name: "Build 'jasper'"
      uses: AlexanderRichert-NOAA/cache-checkout-build@develop
      if: ${{ inputs.jasper-version }}
      with:
        package-name: jasper
        package-org: jasper-software
        cmake-args: ${{ inputs.jasper-cmake-args }}
        git-ref: ${{ inputs.jasper-version }}
        repo-cache: ${{ inputs.repo-cache }}

    - name: "Build 'bacio'"
      uses: AlexanderRichert-NOAA/cache-checkout-build@develop
      if: ${{ inputs.bacio-version }}
      with:
        package-name: NCEPLIBS-bacio
        package-org: NOAA-EMC
        cmake-args: ${{ inputs.bacio-cmake-args }}
        git-ref: ${{ inputs.bacio-version }}
        repo-cache: ${{ inputs.repo-cache }}
